app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('airlines.urls')),
    path('', include('clients.urls')),
    path('', include('cards.urls')),
    path('', include('accounts.urls')),
    path('', include('stock.urls')),
    path('', include('canceled_laps.urls')),
]

stock/urls.py
from django.urls import path
from .views import StockListView, StockCreateView, StockUpdateView, StockDetailView, StockDeleteView


urlpatterns = [
    path('stock/list/', StockListView.as_view(), name='stock_list'),
    path('stock/create/', StockCreateView.as_view(), name='stock_create'),
    path('stock/<int:pk>/detail/', StockDetailView.as_view(), name='stock_detail'),
    path('stock/<int:pk>/update/', StockUpdateView.as_view(), name='stock_update'),
    path('stock/<int:pk>/delete/', StockDeleteView.as_view(), name='stock_delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

class Account(models.Model):
    holder = models.CharField(max_length=200)
    account_login = models.CharField(max_length=200)
    password = models.CharField(max_length=100)
    holder_id = models.CharField(max_length=100)
    account_number = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['holder']

    def __str__(self) -> str:
        return self.account_login

stock/models.py
from django.db import models
from accounts.models import Account
from airlines.models import Airline


class Stock(models.Model):
    account = models.ForeignKey(Account, on_delete=models.PROTECT, related_name='accounts')
    airline = models.ForeignKey(Airline, on_delete=models.PROTECT, related_name='airline')
    annotation = models.TextField(blank=True, null=True)
    date = models.DateField()
    paid_miles = models.PositiveIntegerField(blank=True, null=True)
    origin = models.CharField(max_length=250, blank=True, null=True)
    owner = models.CharField(max_length=200)
    miles_price = models.FloatField(blank=True, null=True)
    current_miles_balance = models.IntegerField()
    due_date = models.DateField()
    updated_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['-date']

    def __str__(self) -> str:
        return self.account__account_login

stock/forms.py
from django import forms
from .models import Stock


class StockForm(forms.ModelForm):

    class Meta:
        model = Stock
        fields = ['account', 'airline', 'annotation', 'date', 'paid_miles', 'origin', 'owner', 'miles_price', 'current_miles_balance', 'due_date']
        widgets = {
            'account': forms.Select(attrs={'class': 'form-control'}),
            'airline': forms.Select(attrs={'class': 'form-control'}),
            'annotation': forms.Textarea(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'paid_miles': forms.NumberInput(attrs={'class': 'form-control'}),
            'origin': forms.TextInput(attrs={'class': 'form-control'}),
            'owner': forms.TextInput(attrs={'class': 'form-control'}),
            'miles_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'current_miles_balance': forms.NumberInput(attrs={'class': 'form-control'}),
            'due_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'})
        }
        labels = {
            'account': 'Conta',
            'airline': 'Companhia Aérea',
            'annotation': 'Anotações sobre a conta',
            'date': 'Data de inclusão',
            'paid_miles': 'Quantidade de milhas pagas para utilização',
            'origin': 'Proveniencia',
            'owner': 'Dono da Conta',
            'miles_price': 'Custo das milhas (Especificar se for diferente)',
            'current_miles_balance': 'Saldo de Milhas no momento',
            'due_date': 'Data de vencimento',
        }

stock/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Stock
from django.urls import reverse_lazy
from .forms import StockForm


class StockListView(ListView):
    model = Stock
    template_name = 'stock_list.html'
    context_object_name = 'stock'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()

        holder = self.request.GET.get('holder')
        account_login = self.request.GET.get('account_login')
        owner  = self.request.GET.get('owner')

        if holder:
            queryset = queryset.filter(account__holder__icontains=holder)

        if account_login:
            queryset = queryset.filter(account__account_login__icontains=account_login)

        if owner:
            queryset = queryset.filter(owner__icontains=owner)

        return queryset
    

class StockCreateView(CreateView):
    model = Stock
    template_name = 'stock_create.html'
    success_url = reverse_lazy('stock_list')
    form_class = StockForm


class StockDetailView(DetailView):
    model = Stock
    template_name = 'stock_detail.html'


class StockUpdateView(UpdateView):
    model = Stock
    template_name = 'stock_update.html'
    success_url = reverse_lazy('stock_list')
    form_class = StockForm


class StockDeleteView(DeleteView):
    model = Stock
    template_name = 'stock_delete.html'
    success_url = reverse_lazy('stock_list')

stock/templates/stock_create.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Adicionar Conta ao Estoque</h3>
    
    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Conta</button>
            </form>
        </div>
    </div>
    <a href="{% url 'stock_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para o Estoque</a>
</div>

{% endblock %}

stock/templates/stock_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Deletar Conta do Estoque</h3>

    <div class="card">
        <div class="card-body">
            <p class="card-text">Tem certeza que deseja exclur a Conta <strong>{{ object.account.account_login }}</strong> de login <strong>{{ object.owner }}</strong></p>

            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-3">Deletar</button> 
            </form>

            <a href="{% url 'account_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para o Estoque</a>
        </div>
    </div>
</div>

{% endblock %}

stock/templates/stock_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Detalhes da Conta</h3>

    <div class="card">
        <div class="card-body">
            <h3 class="card-title">Titular: {{ object.account.holder }}</h3>
            <p class="card-text">Número da Conta: {{ object.account.account_number }}</p>
            <p class="card-text">Login: {{ object.account.account_login }}</p>
            <p class="card-text">Senha: {{ object.account.password }}</p>
            <p class="card-text">Documento do Titular: {{ object.account.holder_id }}</p>
            <p class="card-text">Companhia Aérea: {{ object.airline }}</p>
            <p class="card-text">Data de inclusão: {{ object.date }}</p>
            {% if object.paid_miles %}
                <p class="card-text">Milhas pagas para Aquisição: {{ object.paid_miles }}</p>
            {% endif %}
            {% if object.origin %}
                <p class="card-text">Proveniência: {{ object.origin }}</p>
            {% endif %}
            <p class="card-text">Dono da Conta: {{ object.owner }}</p>
            {% if object.miles_price %}
                <p class="card-text">Preço das Milhas: {{ object.miles_price }}</p>
            {% endif %}
            <p class="card-text">Saldo de Milhas Atual: {{ object.current_miles_price }}</p>
            <p class="card-text">Data de Vencimento: {{ object.due_date }}</p>
        </div>
    </div>
    <a href="{% url 'stock_list' %}" class="btn btn-secondary mt-3">Voltar para o Estoque</a>
</div>

{% endblock %}

stock/templates/stock_list.html
{% extends 'base.html' %}

{% block title %}
Speedmilhas - Estoque
{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col md-6">
        <form method="get" action="{% url 'stock_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="holder" placeholder="Titular da Conta" value="{{ request.GET.holder }}">
                <input type="text" class="form-control" name="account_login" placeholder="Login da Conta" value="{{ request.GET.account_login }}">
                <input type="text" class="form-control" name="owner" placeholder="Dono da Conta" value="{{ request.GET.owner }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>
    
    <div class="col md-6">
        <a href="{% url 'stock_create' %}" class="btn btn-success float-end">
            <i class="bi bi-plus">Adicionar Conta ao Estoque</i>
        </a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Login</th>
                <th>Senha</th>
                <th>Titular</th>
                <th>Data</th>
                <th>Dono da Conta</th>
                <th>Proveniência</th>
                <th>Saldo Atual em Milhas</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for stock_account in stock %}
            <tr>
                <td>{{ stock_account.id }}</td>
                <td>{{ stock_account.account.account_login }}</td>
                <td>{{ stock_account.account.password }}</td>
                <td>{{ stock_account.account.holder }}</td>
                <td>{{ stock_account.date }}</td>
                <td>{{ stock_account.owner }}</td>
                <td>{{ stock_account.origin }}</td>
                <td>{{ stock_account.current_miles_balance }}</td>
                <td>
                    <a href="{% url 'stock_detail' stock_account.id %}" class="btn btn-info btn-sm">
                        <i class="bi bi-eye"></i>
                    </a>

                    <a href="{% url 'stock_update' stock_account.id %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pencil"></i>
                    </a>

                    <a href="{% url 'stock_delete' stock_account.id %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include 'components/_pagination.html' %}

{% endblock %}

stock/templates/stock_update.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Editar Conta no Estoque</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Conta no Estoque</button>
            </form>
        </div>
    </div>

    <a href="{% url 'stock_list' %}" class="btn btn-secondary mt-3"> Cancelar e Voltar para o Estoque</a>
</div>

{% endblock %}